// Enhanced mock data using comprehensive models

import {
  EnhancedProduct,
  EnhancedIngredient,
  EnhancedRecipe,
  RecipeComponent,
  RecipeIngredient,
  OrderEntryProduct,
  mockSectionConfigurations,
  mockDeliveryTurnConfigurations,
} from './enhanced-models';

// ============ ENHANCED INGREDIENTS ============

export const mockEnhancedIngredients: EnhancedIngredient[] = [
  {
    id: 1,
    code: 'FLR001',
    description: 'Wheat Flour',
    uomId: 4,
    uom: 'kg',
    allowExtraQuantity: true,
    extraQuantityPercentage: 5,
    extraQuantityReason: 'Buffer for spillage',
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: true,
    availableInSections: ['Bakery 1', 'Bakery 2', 'Short-Eats 1', 'Short-Eats 2', 'Pastry Section'],
    ingredientType: 'Raw',
    reorderLevel: 500,
    active: true,
  },
  {
    id: 2,
    code: 'CRT001',
    description: 'Carrot',
    uomId: 4,
    uom: 'kg',
    allowExtraQuantity: true,
    extraQuantityPercentage: 15,
    extraQuantityReason: 'Weight loss after cleaning and peeling',
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: true,
    availableInSections: ['Filling Section'],
    ingredientType: 'Raw',
    reorderLevel: 50,
    active: true,
  },
  {
    id: 3,
    code: 'EGG001',
    description: 'Raw Eggs',
    uomId: 3,
    uom: 'Nos',
    allowExtraQuantity: false,
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: false,
    availableInSections: ['Bakery 1', 'Bakery 2', 'Short-Eats 1', 'Short-Eats 2', 'Filling Section', 'Garnish Section'],
    ingredientType: 'Raw',
    reorderLevel: 500,
    active: true,
  },
  {
    id: 4,
    code: 'EGG002',
    description: 'Boiled Eggs',
    uomId: 3,
    uom: 'Nos',
    allowExtraQuantity: false,
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: false,
    availableInSections: ['Garnish Section'],
    ingredientType: 'Processed',
    processingMethod: 'Boiled',
    reorderLevel: 100,
    active: true,
  },
  {
    id: 5,
    code: 'SGR001',
    description: 'Sugar',
    uomId: 4,
    uom: 'kg',
    allowExtraQuantity: true,
    extraQuantityPercentage: 3,
    extraQuantityReason: 'Buffer',
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: true,
    availableInSections: ['Bakery 1', 'Bakery 2', 'Pastry Section'],
    ingredientType: 'Raw',
    reorderLevel: 300,
    active: true,
  },
  {
    id: 6,
    code: 'YST001',
    description: 'Yeast',
    uomId: 1,
    uom: 'g',
    allowExtraQuantity: true,
    extraQuantityPercentage: 5,
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: true,
    availableInSections: ['Bakery 1', 'Bakery 2', 'Short-Eats 1', 'Short-Eats 2'],
    ingredientType: 'Raw',
    reorderLevel: 5000,
    active: true,
  },
  {
    id: 7,
    code: 'BTR001',
    description: 'Butter',
    uomId: 4,
    uom: 'kg',
    allowExtraQuantity: false,
    showInStoresIssueNote: true,
    showInProduction: true,
    showExtraInStoresOnly: false,
    availableInSections: ['Bakery 1', 'Bakery 2', 'Pastry Section'],
    ingredientType: 'Raw',
    reorderLevel: 100,
    active: true,
  },
];

// ============ ENHANCED PRODUCTS ============

export const mockEnhancedProducts: EnhancedProduct[] = [
  {
    id: 1,
    code: 'BR2',
    description: 'Sandwich Bread Large',
    categoryId: 3,
    category: 'Bread',
    productType: 'Finished',
    hasFull: true,
    hasMini: true,
    allowDecimal: false,
    decimalPlaces: 0,
    hasMultiTurn: false,
    deliveryTurns: [1], // 5AM only
    sections: [
      { sectionId: 1, sectionName: 'Bakery 1', componentName: 'Dough', isMainSection: true },
    ],
    roundOffValue: 1,
    standardValue: 'Round to nearest whole number',
    fullWeight: 400,
    miniWeight: 200,
    hasRecipe: true,
    defaultRecipeTemplateId: 1,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 280.0,
    active: true,
  },
  {
    id: 2,
    code: 'BU10',
    description: 'Vegetable Bun',
    categoryId: 4,
    category: 'Bun',
    productType: 'Finished',
    hasFull: true,
    hasMini: true,
    allowDecimal: true,
    decimalPlaces: 2,
    hasMultiTurn: true,
    deliveryTurns: [1, 2, 3], // All turns
    sections: [
      { sectionId: 1, sectionName: 'Bakery 1', componentName: 'Bun', isMainSection: true },
      { sectionId: 5, sectionName: 'Filling Section', componentName: 'Vegetable Curry', isMainSection: false },
    ],
    roundOffValue: 0.25,
    standardValue: '4 buns per batch',
    fullWeight: 80,
    miniWeight: 40,
    hasRecipe: true,
    defaultRecipeTemplateId: 2,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 85.0,
    active: true,
  },
  {
    id: 3,
    code: 'BU12',
    description: 'Fish Bun',
    categoryId: 4,
    category: 'Bun',
    productType: 'Finished',
    hasFull: true,
    hasMini: true,
    allowDecimal: true,
    decimalPlaces: 2,
    hasMultiTurn: true,
    deliveryTurns: [1, 2, 3],
    sections: [
      { sectionId: 1, sectionName: 'Bakery 1', componentName: 'Bun', isMainSection: true },
      { sectionId: 5, sectionName: 'Filling Section', componentName: 'Fish Curry', isMainSection: false },
    ],
    roundOffValue: 0.25,
    fullWeight: 80,
    miniWeight: 40,
    hasRecipe: true,
    defaultRecipeTemplateId: 3,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 90.0,
    active: true,
  },
  {
    id: 4,
    code: 'EGB',
    description: 'Egg Bun',
    categoryId: 4,
    category: 'Bun',
    productType: 'Finished',
    hasFull: true,
    hasMini: true,
    allowDecimal: true,
    decimalPlaces: 2,
    hasMultiTurn: true,
    deliveryTurns: [1, 2],
    sections: [
      { sectionId: 1, sectionName: 'Bakery 1', componentName: 'Bun', isMainSection: true },
      { sectionId: 5, sectionName: 'Filling Section', componentName: 'Filling', isMainSection: false },
      { sectionId: 8, sectionName: 'Garnish Section', componentName: 'Garnish', isMainSection: false },
    ],
    roundOffValue: 0.25,
    standardValue: '4 patties = 1 boiled egg for garnish',
    fullWeight: 85,
    miniWeight: 45,
    hasRecipe: true,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 95.0,
    active: true,
  },
  {
    id: 5,
    code: 'PZ8',
    description: 'Chicken Pizza Large',
    categoryId: 11,
    category: 'Pizza',
    productType: 'Finished',
    hasFull: true,
    hasMini: false,
    allowDecimal: true,
    decimalPlaces: 1,
    hasMultiTurn: false,
    deliveryTurns: [1],
    sections: [
      { sectionId: 7, sectionName: 'Pastry Section', componentName: 'Dough', isMainSection: true },
      { sectionId: 7, sectionName: 'Pastry Section', componentName: 'Topping', isMainSection: true },
    ],
    roundOffValue: 0.5,
    fullWeight: 450,
    hasRecipe: true,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 1850.0,
    active: true,
  },
  {
    id: 6,
    code: 'SAN5',
    description: 'Club Sandwich',
    categoryId: 13,
    category: 'Sandwich',
    productType: 'Finished',
    hasFull: true,
    hasMini: false,
    allowDecimal: true,
    decimalPlaces: 2,
    hasMultiTurn: true,
    deliveryTurns: [1, 2],
    sections: [
      { sectionId: 1, sectionName: 'Bakery 1', componentName: 'Bread', isMainSection: true },
      { sectionId: 5, sectionName: 'Filling Section', componentName: 'Filling', isMainSection: false },
      { sectionId: 8, sectionName: 'Garnish Section', componentName: 'Garnish', isMainSection: false },
      { sectionId: 9, sectionName: 'Packing Section', componentName: 'Packing', isMainSection: false },
    ],
    roundOffValue: 0.5,
    standardValue: '4 pieces per sandwich',
    fullWeight: 250,
    hasRecipe: true,
    requireOpenStock: true,
    enableLabelPrint: true,
    uomId: 3,
    uom: 'Nos',
    unitPrice: 450.0,
    active: true,
  },
];

// ============ ENHANCED RECIPES ============

const vegetableBunDoughIngredients: RecipeIngredient[] = [
  {
    id: 1,
    ingredientId: 1,
    ingredientCode: 'FLR001',
    ingredientName: 'Wheat Flour',
    ingredientType: 'Raw',
    qtyPerUnit: 0.8,
    extraQtyPerUnit: 0.04,
    unit: 'kg',
    storesOnly: false,
    showExtraInStores: true,
    isPercentage: false,
    sortOrder: 1,
  },
  {
    id: 2,
    ingredientId: 5,
    ingredientCode: 'SGR001',
    ingredientName: 'Sugar',
    ingredientType: 'Raw',
    qtyPerUnit: 0.1,
    extraQtyPerUnit: 0.003,
    unit: 'kg',
    storesOnly: false,
    showExtraInStores: true,
    isPercentage: false,
    sortOrder: 2,
  },
  {
    id: 3,
    ingredientId: 6,
    ingredientCode: 'YST001',
    ingredientName: 'Yeast',
    ingredientType: 'Raw',
    qtyPerUnit: 20,
    extraQtyPerUnit: 1,
    unit: 'g',
    storesOnly: false,
    showExtraInStores: true,
    isPercentage: false,
    sortOrder: 3,
  },
  {
    id: 4,
    ingredientId: 3,
    ingredientCode: 'EGG001',
    ingredientName: 'Raw Eggs',
    ingredientType: 'Raw',
    qtyPerUnit: 1,
    extraQtyPerUnit: 0,
    unit: 'Nos',
    storesOnly: true,
    showExtraInStores: false,
    isPercentage: false,
    sortOrder: 4,
  },
];

const vegetableCurryIngredients: RecipeIngredient[] = [
  {
    id: 5,
    ingredientId: 2,
    ingredientCode: 'CRT001',
    ingredientName: 'Carrot',
    ingredientType: 'Raw',
    qtyPerUnit: 1.0,
    extraQtyPerUnit: 0.15, // 15% extra
    unit: 'kg',
    storesOnly: false,
    showExtraInStores: true,
    isPercentage: false,
    sortOrder: 1,
  },
];

export const mockEnhancedRecipes: EnhancedRecipe[] = [
  {
    id: 1,
    productId: 2,
    productCode: 'BU10',
    productName: 'Vegetable Bun',
    components: [
      {
        id: 1,
        productId: 2,
        sectionId: 1,
        sectionName: 'Bakery 1',
        componentName: 'Bun',
        sortOrder: 1,
        ingredients: vegetableBunDoughIngredients,
        isPercentageBased: false,
        additionalIngredients: [],
      },
      {
        id: 2,
        productId: 2,
        sectionId: 5,
        sectionName: 'Filling Section',
        componentName: 'Vegetable Curry',
        sortOrder: 2,
        ingredients: vegetableCurryIngredients,
        isPercentageBased: false,
        additionalIngredients: [],
      },
    ],
    templateId: 2,
    version: 1,
    effectiveFrom: '2026-01-01',
    isActive: true,
    applyRoundOff: true,
    roundOffValue: 0.25,
    roundOffNotes: '4 buns per batch',
  },
  {
    id: 2,
    productId: 4,
    productCode: 'EGB',
    productName: 'Egg Bun',
    components: [
      {
        id: 3,
        productId: 4,
        sectionId: 1,
        sectionName: 'Bakery 1',
        componentName: 'Bun',
        sortOrder: 1,
        ingredients: vegetableBunDoughIngredients, // Same dough as vegetable bun
        isPercentageBased: false,
        additionalIngredients: [],
      },
      {
        id: 4,
        productId: 4,
        sectionId: 5,
        sectionName: 'Filling Section',
        componentName: 'Filling',
        sortOrder: 2,
        ingredients: [
          {
            id: 10,
            ingredientId: 3,
            ingredientCode: 'EGG001',
            ingredientName: 'Raw Eggs',
            ingredientType: 'Raw',
            qtyPerUnit: 0.5,
            extraQtyPerUnit: 0,
            unit: 'Nos',
            storesOnly: false,
            showExtraInStores: false,
            isPercentage: false,
            sortOrder: 1,
          },
        ],
        isPercentageBased: false,
        additionalIngredients: [],
      },
      {
        id: 5,
        productId: 4,
        sectionId: 8,
        sectionName: 'Garnish Section',
        componentName: 'Garnish',
        sortOrder: 3,
        ingredients: [
          {
            id: 11,
            ingredientId: 4,
            ingredientCode: 'EGG002',
            ingredientName: 'Boiled Eggs',
            ingredientType: 'Processed',
            qtyPerUnit: 0.25,
            extraQtyPerUnit: 0,
            unit: 'Nos',
            storesOnly: false,
            showExtraInStores: false,
            isPercentage: false,
            sortOrder: 1,
          },
        ],
        isPercentageBased: false,
        additionalIngredients: [],
      },
    ],
    version: 1,
    effectiveFrom: '2026-01-01',
    isActive: true,
    applyRoundOff: true,
    roundOffValue: 0.25,
    roundOffNotes: '4 patties = 1 boiled egg for garnish',
  },
];

// ============ ORDER ENTRY PRODUCTS ============

export const mockOrderEntryProducts: OrderEntryProduct[] = mockEnhancedProducts.map(
  (product) => ({
    id: product.id,
    code: product.code,
    name: product.description,
    hasFull: product.hasFull,
    hasMini: product.hasMini,
    allowDecimal: product.allowDecimal,
    decimalPlaces: product.decimalPlaces,
    hasMultiTurn: product.hasMultiTurn,
    deliveryTurns: mockDeliveryTurnConfigurations.filter((turn) =>
      product.deliveryTurns.includes(turn.id)
    ),
    freezerBalance: Math.floor(Math.random() * 50) + 10, // Random freezer stock
    isIncluded: true,
    isCustomized: false,
    primarySection: product.sections[0].sectionName,
    allSections: product.sections.map((s) => s.sectionName),
  })
);
