// <auto-generated />
using DMS_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DMS_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519150000_SetDisplayInPOSTrueForAllProducts")]
    partial class SetDisplayInPOSTrueForAllProducts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration only updates data values and does not modify the model structure.
            // The target model is identical to the previous migration's model.
        }
    }
}
