// <auto-generated />
using DMS_Backend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace DMS_Backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260519141900_EnsureAllSchemaColumns")]
    partial class EnsureAllSchemaColumns
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // This migration does not modify the model structure.
            // It only ensures that database columns match the existing entity definitions.
            // The target model is identical to the previous migration's model.
        }
    }
}
